name: Cspell Lint                                                         # Define the name of the workflow

on: [push, pull_request]                                                  # Trigger the workflow on push and pull request events

jobs:                                                                     # Initialise jobs
  lint:                                                                   # Define a job named 'lint'
    runs-on: ubuntu-latest                                                # Specify the type of virtual machine to use (Ubuntu latest version)

    container:                                                            # Initialise container
      image: monkeyknuckles/cspell                                        # Use a Docker container with the hadonlint image

    steps:                                                                # List of steps to execute in the job
      - name: Checkout code                                               # Step name: Checkout code from the repository
        uses: actions/checkout@v3                                         # Use the checkout action to clone the repository

      - name: Copy Cspell config                                          # Step name: Copy cspell configuration file
        run: cp /app/cspell.config.yaml $GITHUB_WORKSPACE                 # Copy the .cspell.config.yaml file from the container to the workspace

      - name: Run Cspell                                                  # Step name: Run Cspell
        run: |
             cspell . --color --language-id en-GB
              
  
      